---
title: "193DS_final"
author: "Mark Oregel"
date: "June 11, 2025"
format: html
  html: 
    toc: true 
    toc-depth: 5
---

### GitHub repository: 
https://github.com/oregel714/ENVS-193DS_spring-2025_final

```{r, message=FALSE}

# reading in packages 
library(tidyverse)
library(here)
library(gt)
library(janitor)
library(readxl)
library(dplyr)
library(MuMIn)
library(DHARMa)
library(lubridate)

# reading in data set 

sst <- read_csv(here("data", "SST_update2023.csv"))

```




# Problem 1: 

a. In part 1, they used a Pearson's correlation test as this would mean that we are trying to understand if there is a correlation between distance from headwater and total nitrogen load. 
In part 2, they used a linear model to determine if there the source of nitrogen influences average nitrogen load. 

b. 




# Problem 2: 

a. Cleaning and Summarizing 

```{r, message=FALSE}

sst_clean <- sst |> # creating new data object from original data set
  select(date, temp) |> # selecting relevant 
  mutate( # changing columns to year and date 
    year = year(date), # specifiying dat as a year  
    month = month(date, label = TRUE, abbr = TRUE) # label and abbreviate the month date 
  ) |> 
  filter(year %in% c(2018, 2019, 2020, 2021, 2022, 2023)) |> # filtering the data for only the specified years 
  select(-date) |> # getting rid of the original date column 
  group_by(year, month) |> # grouping by year and month 
  summarise(mean_monthly_sst = mean(temp, na.rm = TRUE), .groups = "drop")  |> # summarizing  the mean monthly surface temperatures 
  mutate(mean_monthly_sst = round(mean_monthly_sst, 1), year = as.factor(year)) # changing the 'mean_monthly_sst' to be rounded and setting 'year' as a factor 

sst_clean |> # taking the 'sst_clean' object and sampling 5 observations 
  slice_sample(n=5)

str(sst_clean) # displaying the sample 
```



